set_property PACKAGE_PIN AK8	[ get_ports "c0_ddr4_adr[0]" ]
set_property PACKAGE_PIN AM9	[ get_ports "c0_ddr4_adr[1]" ]
set_property PACKAGE_PIN AL8	[ get_ports "c0_ddr4_adr[2]" ]
set_property PACKAGE_PIN AM10 [ get_ports "c0_ddr4_adr[3]" ]
set_property PACKAGE_PIN AK10 [ get_ports "c0_ddr4_adr[4]" ]
set_property PACKAGE_PIN AP11 [ get_ports "c0_ddr4_adr[5]" ]
set_property PACKAGE_PIN AJ11 [ get_ports "c0_ddr4_adr[6]" ]
set_property PACKAGE_PIN AN9	[ get_ports "c0_ddr4_adr[7]" ]
set_property PACKAGE_PIN AG10 [ get_ports "c0_ddr4_adr[8]" ]
set_property PACKAGE_PIN AM8	[ get_ports "c0_ddr4_adr[9]" ]
set_property PACKAGE_PIN AJ10 [ get_ports "c0_ddr4_adr[10]" ]
set_property PACKAGE_PIN AM11 [ get_ports "c0_ddr4_adr[11]" ]
set_property PACKAGE_PIN AL12 [ get_ports "c0_ddr4_adr[12]" ]
set_property PACKAGE_PIN AN8	[ get_ports "c0_ddr4_adr[13]" ]
set_property PACKAGE_PIN AH13 [ get_ports "c0_ddr4_adr[14]" ]
set_property PACKAGE_PIN AL10 [ get_ports "c0_ddr4_adr[15]" ]
set_property PACKAGE_PIN AL11 [ get_ports "c0_ddr4_adr[16]" ]

set_property PACKAGE_PIN AL13 [ get_ports "c0_ddr4_ba[0]" ]
set_property PACKAGE_PIN AN11 [ get_ports "c0_ddr4_ba[1]" ]
set_property PACKAGE_PIN AK13 [ get_ports "c0_ddr4_bg[0]" ]

set_property PACKAGE_PIN AH12 [ get_ports "c0_ddr4_ck_t[0]" ]
set_property PACKAGE_PIN AJ12 [ get_ports "c0_ddr4_ck_c[0]" ]
set_property PACKAGE_PIN AG13 [ get_ports "c0_ddr4_cke[0]" ]

set_property PACKAGE_PIN AH9 [ get_ports "c0_ddr4_act_n" ]

set_property PACKAGE_PIN AH11 [ get_ports "c0_ddr4_reset_n" ]
set_property PACKAGE_PIN AG9 [ get_ports "c0_ddr4_odt[0]" ]
set_property PACKAGE_PIN AK12 [ get_ports "c0_ddr4_cs_n[0]" ]

set_property PACKAGE_PIN G14 [ get_ports "c0_ddr4_dqs_t[0]" ]
set_property PACKAGE_PIN F13 [ get_ports "c0_ddr4_dqs_c[0]" ]
set_property PACKAGE_PIN D16 [ get_ports "c0_ddr4_dm_n[0]" ]
set_property PACKAGE_PIN E17 [ get_ports "c0_ddr4_dq[0]" ]
set_property PACKAGE_PIN D15 [ get_ports "c0_ddr4_dq[1]" ]
set_property PACKAGE_PIN D17 [ get_ports "c0_ddr4_dq[2]" ]
set_property PACKAGE_PIN E14 [ get_ports "c0_ddr4_dq[3]" ]
set_property PACKAGE_PIN E18 [ get_ports "c0_ddr4_dq[4]" ]
set_property PACKAGE_PIN D14 [ get_ports "c0_ddr4_dq[5]" ]
set_property PACKAGE_PIN E15 [ get_ports "c0_ddr4_dq[6]" ]
set_property PACKAGE_PIN C17 [ get_ports "c0_ddr4_dq[7]" ]

set_property PACKAGE_PIN B14 [ get_ports "c0_ddr4_dqs_t[1]" ]
set_property PACKAGE_PIN B13 [ get_ports "c0_ddr4_dqs_c[1]" ]
set_property PACKAGE_PIN A17 [ get_ports "c0_ddr4_dm_n[1]" ]
set_property PACKAGE_PIN B16 [ get_ports "c0_ddr4_dq[8]" ]
set_property PACKAGE_PIN C13 [ get_ports "c0_ddr4_dq[9]" ]
set_property PACKAGE_PIN A15 [ get_ports "c0_ddr4_dq[10]" ]
set_property PACKAGE_PIN A13 [ get_ports "c0_ddr4_dq[11]" ]
set_property PACKAGE_PIN B15 [ get_ports "c0_ddr4_dq[12]" ]
set_property PACKAGE_PIN A12 [ get_ports "c0_ddr4_dq[13]" ]
set_property PACKAGE_PIN A14 [ get_ports "c0_ddr4_dq[14]" ]
set_property PACKAGE_PIN C12 [ get_ports "c0_ddr4_dq[15]" ]

set_property PACKAGE_PIN H18 [ get_ports "c0_ddr4_dqs_t[2]" ]
set_property PACKAGE_PIN H17 [ get_ports "c0_ddr4_dqs_c[2]" ]
set_property PACKAGE_PIN F17 [ get_ports "c0_ddr4_dm_n[2]" ]
set_property PACKAGE_PIN H19 [ get_ports "c0_ddr4_dq[16]" ]
set_property PACKAGE_PIN H16 [ get_ports "c0_ddr4_dq[17]" ]
set_property PACKAGE_PIN G18 [ get_ports "c0_ddr4_dq[18]" ]
set_property PACKAGE_PIN G16 [ get_ports "c0_ddr4_dq[19]" ]
set_property PACKAGE_PIN G19 [ get_ports "c0_ddr4_dq[20]" ]
set_property PACKAGE_PIN F15 [ get_ports "c0_ddr4_dq[21]" ]
set_property PACKAGE_PIN F18 [ get_ports "c0_ddr4_dq[22]" ]
set_property PACKAGE_PIN G15 [ get_ports "c0_ddr4_dq[23]" ]

set_property PACKAGE_PIN L15 [ get_ports "c0_ddr4_dqs_t[3]" ]
set_property PACKAGE_PIN K15 [ get_ports "c0_ddr4_dqs_c[3]" ]
set_property PACKAGE_PIN L20 [ get_ports "c0_ddr4_dm_n[3]" ]
set_property PACKAGE_PIN L16 [ get_ports "c0_ddr4_dq[24]" ]
set_property PACKAGE_PIN J17 [ get_ports "c0_ddr4_dq[25]" ]
set_property PACKAGE_PIN K19 [ get_ports "c0_ddr4_dq[26]" ]
set_property PACKAGE_PIN K17 [ get_ports "c0_ddr4_dq[27]" ]
set_property PACKAGE_PIN L17 [ get_ports "c0_ddr4_dq[28]" ]
set_property PACKAGE_PIN J16 [ get_ports "c0_ddr4_dq[29]" ]
set_property PACKAGE_PIN K18 [ get_ports "c0_ddr4_dq[30]" ]
set_property PACKAGE_PIN J15 [ get_ports "c0_ddr4_dq[31]" ]

set_property PACKAGE_PIN D11 [ get_ports "c0_ddr4_dqs_t[4]" ]
set_property PACKAGE_PIN D10 [ get_ports "c0_ddr4_dqs_c[4]" ]
set_property PACKAGE_PIN H11 [ get_ports "c0_ddr4_dm_n[4]" ]
set_property PACKAGE_PIN C11 [ get_ports "c0_ddr4_dq[32]" ]
set_property PACKAGE_PIN F12 [ get_ports "c0_ddr4_dq[33]" ]
set_property PACKAGE_PIN E12 [ get_ports "c0_ddr4_dq[34]" ]
set_property PACKAGE_PIN F11 [ get_ports "c0_ddr4_dq[35]" ]
set_property PACKAGE_PIN D12 [ get_ports "c0_ddr4_dq[36]" ]
set_property PACKAGE_PIN H12 [ get_ports "c0_ddr4_dq[37]" ]
set_property PACKAGE_PIN H13 [ get_ports "c0_ddr4_dq[38]" ]
set_property PACKAGE_PIN E10 [ get_ports "c0_ddr4_dq[39]" ]

set_property PACKAGE_PIN B10 [ get_ports "c0_ddr4_dqs_t[5]" ]
set_property PACKAGE_PIN A10 [ get_ports "c0_ddr4_dqs_c[5]" ]
set_property PACKAGE_PIN C7 [ get_ports "c0_ddr4_dm_n[5]" ]
set_property PACKAGE_PIN B8 [ get_ports "c0_ddr4_dq[40]" ]
set_property PACKAGE_PIN A6 [ get_ports "c0_ddr4_dq[41]" ]
set_property PACKAGE_PIN B9 [ get_ports "c0_ddr4_dq[42]" ]
set_property PACKAGE_PIN A7 [ get_ports "c0_ddr4_dq[43]" ]
set_property PACKAGE_PIN B11 [ get_ports "c0_ddr4_dq[44]" ]
set_property PACKAGE_PIN B6 [ get_ports "c0_ddr4_dq[45]" ]
set_property PACKAGE_PIN A11 [ get_ports "c0_ddr4_dq[46]" ]
set_property PACKAGE_PIN A8 [ get_ports "c0_ddr4_dq[47]" ]

set_property PACKAGE_PIN E9 [ get_ports "c0_ddr4_dqs_t[6]" ]
set_property PACKAGE_PIN D9 [ get_ports "c0_ddr4_dqs_c[6]" ]
set_property PACKAGE_PIN F7 [ get_ports "c0_ddr4_dm_n[6]" ]
set_property PACKAGE_PIN G10 [ get_ports "c0_ddr4_dq[48]" ]
set_property PACKAGE_PIN F8 [ get_ports "c0_ddr4_dq[49]" ]
set_property PACKAGE_PIN C8 [ get_ports "c0_ddr4_dq[50]" ]
set_property PACKAGE_PIN E8 [ get_ports "c0_ddr4_dq[51]" ]
set_property PACKAGE_PIN F10 [ get_ports "c0_ddr4_dq[52]" ]
set_property PACKAGE_PIN H9 [ get_ports "c0_ddr4_dq[53]" ]
set_property PACKAGE_PIN C9 [ get_ports "c0_ddr4_dq[54]" ]
set_property PACKAGE_PIN G9 [ get_ports "c0_ddr4_dq[55]" ]

set_property PACKAGE_PIN K12 [ get_ports "c0_ddr4_dqs_t[7]" ]
set_property PACKAGE_PIN J11 [ get_ports "c0_ddr4_dqs_c[7]" ]
set_property PACKAGE_PIN M13 [ get_ports "c0_ddr4_dm_n[7]" ]
set_property PACKAGE_PIN J14 [ get_ports "c0_ddr4_dq[56]" ]
set_property PACKAGE_PIN K13 [ get_ports "c0_ddr4_dq[57]" ]
set_property PACKAGE_PIN K14 [ get_ports "c0_ddr4_dq[58]" ]
set_property PACKAGE_PIN K10 [ get_ports "c0_ddr4_dq[59]" ]
set_property PACKAGE_PIN L14 [ get_ports "c0_ddr4_dq[60]" ]
set_property PACKAGE_PIN L12 [ get_ports "c0_ddr4_dq[61]" ]
set_property PACKAGE_PIN J10 [ get_ports "c0_ddr4_dq[62]" ]
set_property PACKAGE_PIN L11 [ get_ports "c0_ddr4_dq[63]" ]